export const CLOSE = "⤫";
export const ADD = "✚";
export const SETTINGS = "⚙️";
export const DELETE = "🗑️";
export const USER = "🙍🏻‍♂️";
export const CALENDER = "🗓️";
export const CLOCK = "⏰";
export const EDIT = "✏️";
export const ARCHIVE = "📦";
export const FOLDER = "📂";
export const CHECK='ꪜ'
